// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['desktop']['App']['Bootstrap']();
}

export function CancelAuthentication() {
  return window['go']['desktop']['App']['CancelAuthentication']();
}

export function CancelLatencyChecks() {
  return window['go']['desktop']['App']['CancelLatencyChecks']();
}

export function CancelPing(arg1) {
  return window['go']['desktop']['App']['CancelPing'](arg1);
}

export function CancelTraceroute(arg1) {
  return window['go']['desktop']['App']['CancelTraceroute'](arg1);
}

export function CheckIPv6() {
  return window['go']['desktop']['App']['CheckIPv6']();
}

export function CheckLatency(arg1) {
  return window['go']['desktop']['App']['CheckLatency'](arg1);
}

export function CheckNAT() {
  return window['go']['desktop']['App']['CheckNAT']();
}

export function CheckOverview() {
  return window['go']['desktop']['App']['CheckOverview']();
}

export function CheckPublicIPv4() {
  return window['go']['desktop']['App']['CheckPublicIPv4']();
}

export function CheckPublicIPv6() {
  return window['go']['desktop']['App']['CheckPublicIPv6']();
}

export function Connect(arg1) {
  return window['go']['desktop']['App']['Connect'](arg1);
}

export function GetAutomaticAuthenticationStatus() {
  return window['go']['desktop']['App']['GetAutomaticAuthenticationStatus']();
}

export function Logout() {
  return window['go']['desktop']['App']['Logout']();
}

export function OpenLink(arg1) {
  return window['go']['desktop']['App']['OpenLink'](arg1);
}

export function RefreshAdapters() {
  return window['go']['desktop']['App']['RefreshAdapters']();
}

export function ResumeAutomaticAuthentication() {
  return window['go']['desktop']['App']['ResumeAutomaticAuthentication']();
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function StartPing(arg1) {
  return window['go']['desktop']['App']['StartPing'](arg1);
}

export function StartTraceroute(arg1) {
  return window['go']['desktop']['App']['StartTraceroute'](arg1);
}
