// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {networkdiag} from '../models';
import {adapters} from '../models';
import {systemnet} from '../models';

export function Bootstrap():Promise<desktop.BootstrapData>;

export function CancelAuthentication():Promise<void>;

export function CancelLatencyChecks():Promise<void>;

export function CancelPing(arg1:string):Promise<void>;

export function CancelTraceroute(arg1:string):Promise<void>;

export function CheckIPv6():Promise<networkdiag.IPv6Result>;

export function CheckLatency(arg1:string):Promise<networkdiag.LatencyProbe>;

export function CheckNAT():Promise<networkdiag.NATResult>;

export function CheckOverview():Promise<networkdiag.OverviewResult>;

export function CheckPublicIPv4():Promise<networkdiag.PublicNetworkInfo>;

export function CheckPublicIPv6():Promise<networkdiag.PublicNetworkInfo>;

export function ClearLocalData():Promise<void>;

export function Connect(arg1:desktop.AuthRequest):Promise<void>;

export function GetAutomaticAuthenticationStatus():Promise<desktop.AutomaticAuthenticationStatus>;

export function Logout():Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function RefreshAdapters():Promise<adapters.Result>;

export function RefreshNetworkInterfaces():Promise<Array<systemnet.NetworkInterface>>;

export function ResumeAutomaticAuthentication():Promise<void>;

export function SaveSettings(arg1:desktop.SettingsRequest):Promise<desktop.SettingsResult>;

export function StartPing(arg1:desktop.PingRequest):Promise<void>;

export function StartTraceroute(arg1:desktop.TraceRequest):Promise<void>;
