// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {networkdiag} from '../models';
import {adapters} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function CancelAuthentication():Promise<void>;

export function CancelLatencyChecks():Promise<void>;

export function CheckIPv6():Promise<networkdiag.IPv6Result>;

export function CheckLatency(arg1:string):Promise<networkdiag.LatencyProbe>;

export function CheckNAT():Promise<networkdiag.NATResult>;

export function CheckOverview():Promise<networkdiag.OverviewResult>;

export function CheckPublicIPv4():Promise<networkdiag.PublicNetworkInfo>;

export function CheckPublicIPv6():Promise<networkdiag.PublicNetworkInfo>;

export function Connect(arg1:main.AuthRequest):Promise<void>;

export function Disconnect():Promise<void>;

export function Logout():Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function RefreshAdapters():Promise<adapters.Result>;

export function SaveSettings(arg1:main.SettingsRequest):Promise<main.SettingsResult>;
